import type { TitleBank } from "../src/titles.ts";
import type { Theme } from "../src/types.ts";

/**
 * The cold-open theme — the 6×6 board a first-time player lands on.
 *
 * ── Why this is generated rather than transcribed ───────────────────────────
 * The Onboarding design draws a specific demo board:
 *
 *   TOASTM / MMORNS / IIUNGO / LRIGMA / KTUAJP / OATSAL
 *
 * with TOAST, MILK, OATS and SOAP, revealing "morning ritual". Those four words
 * do read correctly off that grid, but they occupy only 17 of the 36 cells, so
 * the 19 leftover letters resolve to "MMORNIUNGRIGMTUAJAL" — not
 * "MORNINGRITUAL", which is 13 letters.
 *
 * The design board is illustrative. Shipping it would mean the very first
 * reveal a player ever sees resolves to nonsense — and that reveal is the
 * entire product. So the cold open is generated by the real packer against this
 * pool, seeded so every player gets the same board (D-019).
 *
 * Everything else about O1 follows the design exactly: 6×6, four words, the
 * "Something warm." oblique title, the 306px field, the reveal copy.
 */
export const morningRitual: Theme = {
  id: "morning-ritual",
  name: "Morning ritual",
  // Only one phrase: the cold open must always reveal this, because O3's copy
  // and O7's "the one you just finished" both refer back to it.
  phrases: ["Morning ritual"],
  words: [
    "TOAST", "KETTLE", "BUTTER", "COFFEE", "TEAPOT", "PORRIDGE", "MARMALADE",
    "CEREAL", "YOGHURT", "HONEY", "JUICE", "BACON", "MUESLI", "CROISSANT",
    "OATMEAL", "PANCAKE", "SUGAR", "CREAM", "BREAD", "GRILL", "SPOON",
    "SAUCER", "NAPKIN", "RADIO", "CURTAIN", "SLIPPER", "SHOWER", "ALARM",
    "WINDOW", "KITCHEN", "MORNING", "SUNRISE", "BIRDSONG", "QUIET",
  ],
};

/**
 * O1 shows one oblique title and never changes it: "Something warm."
 *
 * The bank still goes through the normal generator so the leak rules apply —
 * a title that happened to contain a word on the board would spoil the puzzle
 * on the one screen where the player has no idea what they are doing yet.
 */
export const morningTitles: TitleBank = {
  frames: [],
  fillers: [],
  standalone: ["Something warm."],
};
