import { generatePuzzle, readTheme, lettersOnly } from "@wordquilt/generator";
import { morningRitual, morningTitles } from "@wordquilt/generator/data/morning-ritual";
import { fieldHeight } from "@wordquilt/tokens";
import { router } from "expo-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { Pressable, View } from "react-native";
import Animated, { FadeIn, FadeOut, ReduceMotion } from "react-native-reanimated";

import { TraceableBoard } from "@/components/traceable-board";
import { Button, Card, Chip, Text, WordSlot } from "@/components/ui";
import { Screen } from "@/components/ui/screen";
import { duration } from "@/lib/motion";

/**
 * O1 — Cold open.  ·  O2 — Hint tooltip.
 *
 * The app opens directly onto a playable 6×6 grid. No logo, no welcome, no
 * tutorial, no settings, no back and no close: completing the puzzle is the
 * only way forward, and the aha arrives in about ninety seconds — before
 * anything at all is asked of the player.
 *
 * O2 is not a separate route (`/onboarding/1#hint-tooltip`). It is a tooltip
 * that fires once, after 45 seconds with nothing found, dismisses on any touch
 * including one that starts a trace, never blocks input, and happens once per
 * install.
 *
 * ── The board ───────────────────────────────────────────────────────────────
 * Generated, not transcribed from the design (D-019). The design's demo board
 * is illustrative: its four words read correctly but leave 19 leftover cells,
 * which resolve to "MMORNIUNGRIGMTUAJAL" rather than the "MORNING RITUAL" it
 * promises. Since this reveal is the entire product, the board is generated by
 * the real packer with a fixed seed so it actually resolves — and so every
 * player gets the same one.
 */

/** Fixed seed: every first-time player sees the same cold open. */
const COLD_OPEN_SEED = 1;

/** The design's timing: the tooltip fires at 45s with nothing found. */
const HINT_AFTER_MS = 45_000;

export default function ColdOpen() {
  const puzzle = useMemo(() => {
    const result = generatePuzzle({
      theme: morningRitual,
      titles: morningTitles,
      spec: { rows: 6, cols: 6, wordCount: 4 },
      seed: COLD_OPEN_SEED,
    });
    if (!result.ok) throw new Error(`cold open failed to generate: ${result.reason}`);
    return result.puzzle;
  }, []);

  const words = puzzle.placements.map((p) => p.word);
  const [found, setFound] = useState<string[]>([]);
  const [showTooltip, setShowTooltip] = useState(false);
  const tooltipShown = useRef(false);

  // O2: fires once, at 45s, only if nothing has been found yet.
  useEffect(() => {
    if (found.length > 0 || tooltipShown.current) return;
    const t = setTimeout(() => {
      if (found.length === 0) {
        setShowTooltip(true);
        tooltipShown.current = true;
      }
    }, HINT_AFTER_MS);
    return () => clearTimeout(t);
  }, [found.length]);

  // The last word closes the puzzle out. The Reveal owns the hold, not this
  // screen, so we hand straight over.
  useEffect(() => {
    if (found.length === words.length) {
      router.replace("/onboarding/3");
    }
  }, [found.length, words.length]);

  const sew = (word: string) => {
    setShowTooltip(false);
    setFound((f) => (f.includes(word) ? f : [...f, word]));
  };

  return (
    <Pressable onPress={() => setShowTooltip(false)} className="flex-1">
      <Screen
        field={fieldHeight.standard}
        header={
          <View className="gap-4">
            <View className="h-[52px] flex-row items-center gap-3">
              <View className="flex-1" />
              <Chip label={`${found.length} of ${words.length}`} />
            </View>
            <Text variant="oblique">{puzzle.obliqueTitle}</Text>
            <View className="flex-row flex-wrap justify-center gap-[9px]">
              {words.map((word) => (
                <WordSlot key={word} word={word} found={found.includes(word)} />
              ))}
            </View>
          </View>
        }
        footer={
          <View className="flex-row items-center gap-[14px]">
            <Button label="Hint" size="lg" onPress={() => setShowTooltip(false)} />
            <View className="flex-1 gap-[2px]">
              <Text variant="listTitle">3 free today</Text>
              <Text variant="meta">Or hold anywhere on the grid</Text>
            </View>
          </View>
        }
      >
        <View className="h-[44px]" />
        <TraceableBoard puzzle={puzzle} found={found} onFound={sew} />

        {/* The reserved band. It holds its height whether or not anything is in
            it, so hint feedback never shifts the grid (constraint 7). */}
        <View className="h-[32px] justify-center">
          {showTooltip && (
            <Animated.View
              entering={FadeIn.duration(duration.enter).reduceMotion(ReduceMotion.System)}
              exiting={FadeOut.duration(duration.reduced).reduceMotion(ReduceMotion.System)}
              className="self-center"
            >
              <Card animate={false} className="px-4 py-2">
                <Text variant="meta" className="text-ink">
                  Stuck? A hint opens one letter.
                </Text>
              </Card>
            </Animated.View>
          )}
        </View>
        <View className="flex-1" />
      </Screen>
    </Pressable>
  );
}

/** Exported so O3 can assert it is revealing the board the player just solved. */
export { COLD_OPEN_SEED };
export const coldOpenResolves = (p: Parameters<typeof readTheme>[0]) =>
  readTheme(p) === lettersOnly(p.theme);
